name: lokerapps
description: "A new Flutter project."


publish_to: 'none'













version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'







dependencies:
  # Firebase
  firebase_core: ^2.25.4
  firebase_database: ^10.3.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.15.5
  cloud_functions: ^4.6.8
  firebase_storage: ^11.6.9

  webview_flutter: ^2.0.13
  dio: ^5.0.0 # Check for the latest version on pub.dev

  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^11.3.0
  scoped_model: ^2.0.0

  intl: ^0.18.1
  equatable: ^2.0.5
  provider: ^6.1.1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  go_router: ^12.1.3
  http: ^1.2.0
  #Payment Gateway
  midtrans_sdk: ^0.4.0
  flutter_dotenv: ^5.1.0

  async: ^2.10.0 # Add this line


  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/loker_logo.png"
  min_sdk_android: 21

  flutter_test:
    sdk: flutter






  flutter_lints: ^2.0.0





flutter:




  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assetresult/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 800
          style: italic
   
   
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
